workflows:
  friday_android_build:
    name: Friday Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      vars:
        JAVA_VERSION: 17

    scripts:
      - name: Check Gradle Wrapper
        script: |
          ls -la
          ls -la gradle || true
          ls -la gradle/wrapper || true

      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk